# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.206
neo_version_range=[21.1.50,)
loader_version_range=[4,)
mod_dev_gradle=2.0.134

## Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod Properties
mod_version=5.0.9
edivadlib_id=5491721
edivadlib_version_range=[3.0.0,)
refinedstorage_version_range=[2.0.0,)

# Dependencies
jei_version=19.21.0.247
top_version=6106998
rs_version=2.0.1
co_version=2.1.2.5
jade_id=6198776
