modLoader="javafml"
loaderVersion="[40,)"
license="GNU AGPLv3"

[[mods]]
modId="extrastorage"
version="${file.jarVersion}"
displayName="Extra Storage"
updateJSONURL="https://raw.githubusercontent.com/Edivad99/mod-version-controll/master/extrastorage_update.json"
issueTrackerURL="https://github.com/Edivad99/ExtraStorage/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/extrastorage"
authors="edivad"
description="Extra Storage adds new blocks to Refined Storage"


[[dependencies.extrastorage]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrastorage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrastorage]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.10.2,)"
    ordering="AFTER"
    side="BOTH"