name: 'Release'

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Build
        run: ./gradlew build --max-workers 1

      - name: Make Changelog
        run: ./gradlew makeChangelog --max-workers 1

      - name: Publish
        run: ./gradlew publishMods --max-workers 1
